# Generated by Django 6.1.1 on 2026-09-17 04:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_eventimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(default='', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='event',
            name='ends_at',
            field=models.DateTimeField(verbose_name='Дата и время завершения проведения'),
        ),
        migrations.AlterField(
            model_name='event',
            name='publication_at',
            field=models.DateTimeField(verbose_name='Дата и время публикации'),
        ),
        migrations.AlterField(
            model_name='event',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(25)], verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='event',
            name='starts_at',
            field=models.DateTimeField(verbose_name='Дата и время начала проведения'),
        ),
    ]
