# Generated by Django 6.1.1 on 2026-09-19 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_description_alter_event_ends_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название места'),
        ),
    ]
