# Generated by Django 6.1.1 on 2026-09-17 06:30

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0003_alter_event_description_alter_event_ends_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature_in_c', models.IntegerField(validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(100)], verbose_name='Температура по шкале Цельсия')),
                ('humidity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Влажность воздуха, в %')),
                ('pressure', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Атмосферное давление, в мм ртутного столба')),
                ('wind_direction', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(360)], verbose_name='Направление ветра')),
                ('wind_speed', models.DecimalField(decimal_places=1, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))], verbose_name='Скорость ветра, в м/с')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weathers', to='events.venue', verbose_name='Место проведения')),
            ],
        ),
    ]
